version: '3.4'

services:
  api1:
    image: ${DOCKER_REGISTRY-}api1
    build:
      context: .
      dockerfile: Api1/Dockerfile
    networks:
      - api

  api2:
    image: ${DOCKER_REGISTRY-}api2
    build:
      context: .
      dockerfile: Api2/Dockerfile
    networks:
      - api
networks:
  api:
    driver: bridge

